### ISSUE TITLE
adding skins to a list

### ISSUE THREAD

**Issue by JustSomeGamer000** [Fuzss/strawstatues#9]
### Suggestion (Required)

Alright, let me paint you a picture: you've just made a schmexy house in minecraft with everything you could ever wish for (bedroom, armory, underground pool you name it!) and you want to put a statue of herobrine outside on the porch ('cause why the hell not!) so you put down a straw statue and open the menu, you then scroll to the properties tab to change the name to herobrine but then, as you look at the statue you realize... it's herobrine... but with a cat suit! (I know right?!). You then look through a website called namemc and scroll through herobrine skins, you then find one that you like and scroll through the usernames to find one that still uses the skin because if you change your skin, it updates and changes the statue to the skin that they are currently using.

Okay, my point is that I want there to be a way where I can download a skin, put it into a folder and have it so that I can use that skin from within the properties menu in the form of a list so that the risk of someone changing their skin is removed

a second way around this (if it's possible) is that the mod can take skins from the launcher and then paste them to the mods properties tab.

I think that this update should be released in a 1.19.3 port (if you want tho.)

anyways that's my suggestion... bye!

**Comment by Fuzss** [comment]
Thanks for the suggestion! This approach isn't really feasible unfortunately, it's problematic when playing on a server, since other players won't have the skin and won't be able to see it.

Mojang 'fixed' this for player heads by making them keep the skin they were originally set to, even after the account has changed to a different skin. I tried to add this behavior to Straw Statues, too, but according to some reports it doesn't work yet. So I'll have to look back into that at some point.

**Comment by JustSomeGamer000** [comment]
dammm that sucks😂, oh well! Thanks for trying!!
